[project]
name = "stream"
version = "0.1.01"
description = "a simple text to text conv using groq api and using gpt oss "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "langchain[groq]>=1.2.4",
    "python-decouple>=3.8",
    "python-dotenv>=1.2.1",
]
