[project]
name = "stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "langchain[groq]>=1.2.4",
    "python-decouple>=3.8",
    "python-dotenv>=1.2.1",
]
